id: "ollama_lucie_7b"
label: "Ollama Lucie 7B Instruct (discarded for now)"
model_config:
  provider: "ollama"
  model: "OpenLLM-France/Lucie-7B-Instruct:latest"
  base_url: "http://192.168.0.19:11434"
  generation_config:
    temperature: 0.7
    top_p: null
    top_k: null
    max_output_tokens: 2048
parameters:
  structured_output: true
  parallel:
    workers: 1
