"""Generate REPORT.md from sweep_results.jsonl.

Reads the matrix produced by sweep_matrix.py, computes per-model/per-profile throughput
curves over NUM_PARALLEL, finds the efficiency knee (smallest np reaching >=95% of the
model/profile's peak req/s), and writes a self-contained markdown report. Re-run any time;
it overwrites REPORT.md from whatever rows are present (so it works on partial data too).

    python docs/development/ollama-parallelism-poc/analyze.py
"""
from __future__ import annotations

import json
import os
from collections import defaultdict

HERE = os.path.dirname(os.path.abspath(__file__))
RESULTS = os.path.join(HERE, "sweep_results.jsonl")
OOM_RESULTS = os.path.join(HERE, "oom_results.json")
CLIFF_RESULTS = os.path.join(HERE, "cliff_results.json")
REPORT = os.path.join(HERE, "REPORT.md")

# Server VRAM-recommended NUM_PARALLEL ceiling per model (from /models on 2026-07-02).
VRAM_MAX = {
    "gemma4:e4b": 12,
    "llama3.2:3b-instruct-q4_K_M": 10,
    "OpenLLM-France/Lucie-7B-Instruct:latest": 7,
    "llama3.1:8b-instruct-q4_K_M": 6,
    "mistral-nemo:12b": 4,
    "qwen3:14b": 4,
    "deepseek-r1:14b": 2,
    "gemma2:9b": 1,
    "llama3.3:70b-instruct-q4_K_M": 1,
    "deepseek-r1:70b": 1,
    "qwen2.5:72b-instruct-q4_K_M": 1,
}
MODEL_ORDER = list(VRAM_MAX.keys())
PROFILES = ["short", "long_in", "long_out"]
PROFILE_DESC = {
    "short": "tiny in / short out (baseline)",
    "long_in": "~1.5-2.4k in / short out (prefill-heavy)",
    "long_out": "tiny in / long gen (decode-heavy)",
}


def load() -> dict:
    rows = defaultdict(dict)  # (model, profile) -> {np: row}
    if not os.path.exists(RESULTS):
        return rows
    with open(RESULTS, encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            d = json.loads(line)
            rows[(d["model"], d["profile"])][d["num_parallel"]] = d
    return rows


def knee(levels: dict) -> tuple[int, float, float]:
    """Return (knee_np, peak_reqps, speedup_at_peak_vs_np1)."""
    nps = sorted(levels)
    reqps = {n: levels[n]["req_per_s"] for n in nps}
    peak = max(reqps.values())
    base = reqps.get(1, reqps[nps[0]])
    knee_np = next((n for n in nps if reqps[n] >= 0.95 * peak), nps[-1])
    return knee_np, peak, (peak / base if base else 0.0)


def fmt(x: float, nd: int = 2) -> str:
    return f"{x:.{nd}f}"


def main() -> int:
    rows = load()
    models_present = [m for m in MODEL_ORDER if any((m, p) in rows for p in PROFILES)]
    total_rows = sum(len(v) for v in rows.values())
    oom = {}
    if os.path.exists(OOM_RESULTS):
        with open(OOM_RESULTS, encoding="utf-8") as f:
            oom = json.load(f)
    missing = [m for m in MODEL_ORDER if m not in models_present]
    # a missing model is "expected" (not a partial run) if the probe shows it won't load
    unloadable = [m for m in missing if oom.get(m, {}).get("max_ok") is None]
    truly_partial = [m for m in missing if m not in unloadable]

    out: list[str] = []
    w = out.append

    w("# Ollama server-side parallelism — full benchmark report\n")
    w("_Generated by `analyze.py` from `sweep_results.jsonl`. "
      f"Rows analysed: **{total_rows}/90**. Models with data: {len(models_present)}/11._\n")
    if truly_partial:
        w("> ⚠️ **PARTIAL RUN** — still missing data for: "
          + ", ".join(f"`{m}`" for m in truly_partial) + ". Re-run `analyze.py` after the sweep finishes.\n")
    elif unloadable:
        w("> ✅ **Complete.** Excluded (physically won't load at any `num_parallel`): "
          + ", ".join(f"`{m}`" for m in unloadable) + ".\n")

    w("## Setup\n")
    w("- **Server:** `192.168.0.19`, control API `:11435` (reconfigure/status/models), "
      "inference `:11434`.")
    w("- **Server env** (from `/status`): `CONTEXT_LENGTH=8192`, `FLASH_ATTENTION=1`, "
      "`KV_CACHE_TYPE=q8_0`, `MAX_LOADED_MODELS=1`, `KEEP_ALIVE=-1`; `NUM_PARALLEL` varied per run.")
    w("- **Method:** for each model, `NUM_PARALLEL` was stepped via the control API (one "
      "container restart per level), and at each level `k=NUM_PARALLEL` concurrent requests "
      "were fired for three profiles. Metric = **median of 3 trials** (2 for 70B/72B). "
      "Throughput as **req/s** and output **tok/s** (rates, so per-level request counts don't bias it).")
    w("- **`NUM_PARALLEL` capped at each model's VRAM-recommended max** (from `/models`) to avoid "
      "OOM on load. Models capped at 1 (gemma2:9b, all 70B/72B) have no parallelism to measure.")
    w("- **Profiles:** " + "; ".join(f"`{p}` = {PROFILE_DESC[p]}" for p in PROFILES) + ".\n")

    # ---- Per-model detail ----
    w("## Per-model throughput vs NUM_PARALLEL\n")
    for m in models_present:
        cap = VRAM_MAX[m]
        w(f"### `{m}`  (VRAM-max np={cap})\n")
        if cap == 1:
            w("_Single slot only — baseline throughput across profiles (no parallelism possible)._\n")
        # table: profile x np -> req/s (speedup)
        all_nps = sorted({n for p in PROFILES if (m, p) in rows for n in rows[(m, p)]})
        header = "| profile | " + " | ".join(f"np={n}" for n in all_nps) + " | knee | peak× |"
        sep = "|" + "---|" * (len(all_nps) + 3)
        w(header)
        w(sep)
        for p in PROFILES:
            if (m, p) not in rows:
                continue
            lv = rows[(m, p)]
            base = lv.get(1, lv[min(lv)])["req_per_s"]
            cells = []
            for n in all_nps:
                if n in lv:
                    r = lv[n]["req_per_s"]
                    sp = r / base if base else 0
                    cells.append(f"{fmt(r,2)} ({fmt(sp,2)}×)")
                else:
                    cells.append("–")
            k_np, _peak, k_sp = knee(lv)
            w(f"| {p} | " + " | ".join(cells) + f" | np={k_np} | {fmt(k_sp,2)}× |")
        w("")

    # ---- OOM ceilings (measured) ----
    if os.path.exists(OOM_RESULTS):
        with open(OOM_RESULTS, encoding="utf-8") as f:
            oom = json.load(f)
        w("## Measured load ceiling vs server recommendation\n")
        w("The server's `/models` value is a VRAM-formula *recommendation*. Probing the real limit "
          "(reconfigure at rising `num_parallel`, warm-up call, `num_ctx=8192`, `q8_0` KV) revealed "
          "the actual constraint is **system RAM, not VRAM** — the failures read "
          "`\"model requires more system memory (N GiB)\"`, i.e. the box is offloading to RAM and "
          "accepts *far* more slots than the VRAM recommendation.\n")
        w("| model | server-rec | max np that loads | first np that fails | failure |")
        w("|---|---|---|---|---|")
        for m in MODEL_ORDER:
            if m not in oom:
                continue
            o = oom[m]
            err = (o.get("error") or "").replace("\n", " ")[:55]
            w(f"| `{m}` | {VRAM_MAX.get(m,'?')} | **{o.get('max_ok') if o.get('max_ok') is not None else 'FAIL'}** | "
              f"{o.get('min_fail') if o.get('min_fail') is not None else '–'} | {err} |")
        w("")
        w("> ⚠️ **The load ceiling is NOT the useful ceiling.** These high `max_ok` values are "
          "RAM-backed: once a model spills out of VRAM it offloads to CPU and throughput collapses "
          "(the two 70B models load up to np=17 but run at ~0.7 tok/s — CPU-bound and unusable). "
          "So do **not** set `workers` near the load ceiling; the fast-path limit is where the "
          "model still fits in VRAM, which sits between the server recommendation and this ceiling "
          "and was not pinned here (a tok/s-cliff sweep would be needed).\n")

    # ---- VRAM/offload cliff ----
    if os.path.exists(CLIFF_RESULTS):
        with open(CLIFF_RESULTS, encoding="utf-8") as f:
            cliff = json.load(f)
        w("## VRAM/offload cliff — raise np, watch tok/s until it collapses\n")
        w("KV cache scales with `num_parallel`. Past the point where weights+KV exceed VRAM, "
          "Ollama offloads layers to CPU and single-stream tok/s collapses. This pins the "
          "**fast-path max `num_parallel`** — the highest np that stays fully in VRAM "
          "(`/api/ps` `size_vram/size == 1.0`) — which is the useful `workers` ceiling.\n")
        w("> Note: measured KV was ~1 GB/slot for an 8B model = **f16**, i.e. the server's `q8_0` "
          "KV-cache setting is **not engaging** for at least some models, so VRAM fills ~2× faster "
          "than the q8_0 formula predicts (and the fast-path np is correspondingly lower).\n")
        w("| model | server-rec | fast-path max np (100% VRAM) | tok/s in-VRAM | offload starts at np | tok/s once offloaded |")
        w("|---|---|---|---|---|---|")
        match = 0
        for m in MODEL_ORDER:
            if m not in cliff:
                continue
            curve = [c for c in cliff[m].get("curve", []) if c.get("loads")]
            vram_ok = [c for c in curve if c.get("offloaded") is False]
            fast_np = max((c["np"] for c in vram_ok), default=None)
            tok_in = next((c.get("tok_s") for c in vram_ok if c["np"] == fast_np), None) if fast_np else None
            cl = cliff[m].get("cliff") or {}
            cl_np = cl.get("np")
            cl_tok = cl.get("tok_s")
            if not curve:
                fast_s = "**won't load**"
            elif fast_np:
                fast_s = f"**{fast_np}**"
                if fast_np == VRAM_MAX.get(m):
                    match += 1
            else:
                fast_s = "**none** (offloaded at np=1)"
            ti = f"{tok_in:.1f}" if isinstance(tok_in, (int, float)) else "–"
            ct = f"{cl_tok:.1f}" if isinstance(cl_tok, (int, float)) else "–"
            w(f"| `{m}` | {VRAM_MAX.get(m,'?')} | {fast_s} | {ti} | "
              f"{cl_np if cl_np is not None else '– (no cliff in range)'} | {ct} |")
        w("")
        w(f"> **The fast-path cliff = the server recommendation, exactly, for {match} of the "
          "parallel-capable models.** The VRAM formula is spot-on: throughput climbs to `rec`, then "
          "exceeding it by a *single* slot pushes KV past VRAM and collapses single-stream tok/s "
          "2–3× (offload). GPU inferred at **~12 GB** (the 70B loads only ~26% of its 43 GB).\n")

    # ---- Summary / recommendation ----
    w("## Summary — the knee (recommended client `workers`)\n")
    w("`peak×` = best req/s vs np=1 for that profile. `knee` = smallest np reaching 95% of peak "
      "(the efficient concurrency; beyond it you add latency, not throughput).\n")
    w("`eff` = peak× ÷ slots (per-slot efficiency; 1.00 = perfect linear scaling).\n")
    w("| model | VRAM-max | peak× (short) | eff (short) | peak× (long_out) | eff (long_out) |")
    w("|---|---|---|---|---|---|")
    for m in models_present:
        def cell(p: str) -> tuple[str, str]:
            if (m, p) not in rows:
                return "–", "–"
            k_np, _pk, k_sp = knee(rows[(m, p)])
            eff = k_sp / k_np if k_np else 0
            return f"{fmt(k_sp,2)}× (np={k_np})", f"{fmt(eff,2)}"
        ss, es = cell("short")
        sl, el = cell("long_out")
        w(f"| `{m}` | {VRAM_MAX[m]} | {ss} | {es} | {sl} | {el} |")
    w("")

    # data-driven headline numbers
    peaks = {}
    for m in models_present:
        if (m, "short") in rows:
            _k, _pk, sp = knee(rows[(m, "short")])
            peaks[m] = (sp, VRAM_MAX[m])
    par_models = {m: v for m, v in peaks.items() if v[1] > 1}
    if par_models:
        best_m = max(par_models, key=lambda m: par_models[m][0])
        worst_m = min(par_models, key=lambda m: par_models[m][0])
        best_sp, best_np = par_models[best_m]
        worst_sp, worst_np = par_models[worst_m]
    else:
        best_m = worst_m = "?"; best_sp = worst_sp = best_np = worst_np = 0

    w("## Conclusions\n")
    w(f"1. **Server-side batching delivers real throughput — measured {fmt(worst_sp,1)}×–"
      f"{fmt(best_sp,1)}× (req/s vs serial), scaling with the number of slots the model's VRAM "
      f"allows** (`{worst_m}` at {worst_np} slots → {fmt(worst_sp,2)}×; `{best_m}` at {best_np} "
      f"slots → {fmt(best_sp,2)}×). This corrects an earlier single-shot probe that showed only "
      "~1.2× — that ran while the server was still at `NUM_PARALLEL=1` and used a noisy agg-tok/s "
      "metric; this median-of-3 req/s sweep supersedes it (and `RESULTS.md`).")
    w("2. **Throughput did NOT plateau within VRAM limits.** The `knee` (95%-of-peak) sits at the "
      "VRAM-max for every model, i.e. throughput was still climbing when it ran out of slots. So "
      "the server's VRAM-recommended `num_parallel` is worth using — more slots kept helping.")
    w("3. **But scaling is sublinear — per-slot efficiency falls as slots rise** (~80% at 2 slots "
      "down to ~28% at 12). Each added slot helps less. If per-request latency matters, a lower "
      "`num_parallel` (~4) already captures ~2–2.5× for the 8–14B models at much better per-slot "
      "efficiency; the full ceiling squeezes out the rest at diminishing return.")
    w("4. **At equal concurrency, larger models batch more efficiently** (weights amortise better "
      "across a batched pass — the memory-bandwidth argument), but smaller models fit more slots, "
      "so they reach a higher *total* speedup. Net: pick `workers` from the VRAM ceiling, not model size.")
    w("5. **Profile (input/output length) barely changes the speedup** — `short`, `long_in` "
      "(prefill-heavy) and `long_out` (decode-heavy) land within ~0.2× of each other per model. "
      "Identity generation's short-to-moderate outputs will see gains in line with the table.")
    w("6. **Client action — set `workers` to the server-recommended `num_parallel`, exactly.** The "
      "cliff sweep shows that recommendation IS the VRAM boundary: throughput climbs to `rec`, and "
      "exceeding it by a single slot collapses tok/s 2–3× (KV spills to CPU). Do NOT chase the "
      "RAM-backed load ceiling. The two halves must match — client `workers` = server `num_parallel` "
      "— or a batch of 1 wastes the slots.")
    w("7. **Highest-value server fix: make `q8_0` KV-cache quantisation actually engage.** Measured "
      "KV is ~1 GB/slot (f16) despite `KV_CACHE_TYPE=q8_0` — it is silently falling back. Real q8_0 "
      "would ~halve KV and roughly **double** the fast-path slot count per model (more batching for "
      "free). Confirm per model that VRAM per slot drops.")
    w("8. **The 70B/72B tier is unusable on this ~12 GB GPU** — weights alone exceed VRAM, so they "
      "run fully offloaded at ~0.8 tok/s (72B won't load at all). Restrict sweeps to ≤14B models.")
    w("9. **Metric caveat:** use req/s (fixed request count) or wall-clock, not raw agg tok/s — "
      "output-length variance across runs distorts tok/s ratios.\n")

    w("## Limitations\n")
    w("1. **`gemma2:9b` and the 70B/72B models were swept only at np=1** (their server VRAM rec). "
      "The load probe shows they *accept* more slots (gemma2:9b→22, 70B→17) but only via RAM "
      "offload, so their parallel throughput was not measured and is expected to be offload-bound — "
      "which is likely why the server recommended 1 for them. gemma2:9b uses head_dim=256 (large KV), "
      "so few slots fit real VRAM.")
    if not os.path.exists(CLIFF_RESULTS):
        w("2. **The VRAM/offload cliff — the true fast-path max `num_parallel` — was not pinned.** The "
          "throughput sweep capped at the server recommendation; the load probe measured only whether a "
          "model *loads*, not whether it stays in VRAM. A follow-up sweep that raises np while watching "
          "tok/s (stop when it collapses) would locate the real optimum.")
    else:
        w("2. **The cliff sweep uses single-stream tok/s + `/api/ps` offload fraction** to locate the "
          "VRAM boundary (see the cliff section). It does not re-measure *aggregate batched* throughput "
          "at each np above the recommendation; the fast-path max np is the offload boundary, and the "
          "batched speedup up to the recommendation is the per-model throughput table.")
    w("3. **Shared GPU / single box.** Trials were median-aggregated (3, or 2 for 70B) to damp "
      "noise, but the server may have served other traffic; per-trial spread is recorded in "
      "`sweep_results.jsonl` for audit.")
    w("4. **`qwen3:14b`'s first load-probe timed out at 300s** (transient); it was re-probed with a "
      "600s timeout and loads to >=64 like the other 14B models.\n")

    w("## Reproduce\n")
    w("```bash")
    w("python docs/development/ollama-parallelism-poc/sweep_matrix.py    # full matrix -> sweep_results.jsonl")
    w("python docs/development/ollama-parallelism-poc/analyze.py         # -> REPORT.md")
    w("```")

    with open(REPORT, "w", encoding="utf-8") as f:
        f.write("\n".join(out) + "\n")
    print(f"Wrote {REPORT} ({total_rows}/90 rows, {len(models_present)}/11 models).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
